name: Auto Merge PRs labeled automerge

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: "${{ github.event.label.name == 'automerge' }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge pull request
        uses: peter-evans/merge-pull-request@v4
        with:
          commit-title: 'Auto-merge PR #${{ github.event.pull_request.number }}'
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
